### ISSUE TITLE
question

### ISSUE THREAD

**Issue by shenhaiyoulan** [fei-hdu/genre#2]
what is the meaning of the number  in the last column?
![image](https://user-images.githubusercontent.com/67261218/135758032-6fb2bc2b-edf1-406e-bf29-f6fe00e514b5.png)
Thanks!

**Comment by shaonianruntu** [comment]
> what is the meaning of the number in the last column?
> ![image](https://user-images.githubusercontent.com/67261218/135758032-6fb2bc2b-edf1-406e-bf29-f6fe00e514b5.png)
> Thanks!

Hi shenhaiyoulan,

This column is meaningless, we didn't actually use it in the project.
You can just ignore or delete it.

If there is no more problem, can you help to close this issue?

Thanks
Nan

**Comment by shaonianruntu** [comment]
> > what is the meaning of the number in the last column?
> > ![image](https://user-images.githubusercontent.com/67261218/135758032-6fb2bc2b-edf1-406e-bf29-f6fe00e514b5.png)
> > Thanks!
> 
> Hi shenhaiyoulan,
> 
> This column is meaningless, we didn't actually use it in the project. You can just ignore or delete it.
> 
> Thanks Nan



> what is the meaning of the number in the last column?
> ![image](https://user-images.githubusercontent.com/67261218/135758032-6fb2bc2b-edf1-406e-bf29-f6fe00e514b5.png)
> Thanks!

If there is no more problem, can you help to close this issue?

Thanks
Nan

**Comment by shenhaiyoulan** [comment]
OH! Anothor question!  what is the difference between mat and mat2?
![image](https://user-images.githubusercontent.com/67261218/146368318-545632fe-0130-4553-a7ae-77bb503c91da.png)

**Comment by shaonianruntu** [comment]
> OH! Anothor question! what is the difference between mat and mat2?
> ![image](https://user-images.githubusercontent.com/67261218/146368318-545632fe-0130-4553-a7ae-77bb503c91da.png)

Hi shenhaiyoulan

`mat` means the parsing results of the photo images.
`mat2` means the parsing results of the sketch images.

Thanks
Nan

**Comment by shenhaiyoualn** [comment]
THANKS!!!
