### ISSUE TITLE
about the parsing!

### ISSUE THREAD

**Issue by shenhaiyoualn** [fei-hdu/genre#3]
你好，我注意到您使用的人脸分割图是一个19维度的mat向量，但是您提供的链接好像与此不太一样，我想要再其他数据集上进行实验，可以麻烦您告知一下数据的处理方法嘛。 
谢谢！！！

**Comment by shaonianruntu** [comment]
> 你好，我注意到您使用的人脸分割图是一个19维度的mat向量，但是您提供的链接好像与此不太一样，我想要再其他数据集上进行实验，可以麻烦您告知一下数据的处理方法嘛。
> 谢谢！！！

Hi shenhaiyoualn

This is the link of our face parsing model: https://github.com/jehovahxu/face-parsing.PyTorch

BTW, If there is no more problem, can you help to close this issue ?

Thanks & Regards
Nan
